"""empty message

Revision ID: 3ceff059ad8e
Revises: 7af9ab629f75
Create Date: 2023-11-14 15:52:43.843970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ceff059ad8e'
down_revision = '7af9ab629f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2005', sa.String(length=255), nullable=True))

    with op.batch_alter_table('profit_and_loss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2005', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profit_and_loss', schema=None) as batch_op:
        batch_op.drop_column('year_2005')

    with op.batch_alter_table('balance_sheet', schema=None) as batch_op:
        batch_op.drop_column('year_2005')

    # ### end Alembic commands ###
